2022-02-04 16:05:30,687 INFO    MainThread:31917 [wandb_setup.py:_flush():71] setting env: {'api_key': '***REDACTED***'}
2022-02-04 16:05:30,688 INFO    MainThread:31917 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-04 16:05:30,688 INFO    MainThread:31917 [wandb_init.py:_log_setup():371] Logging user logs to /home/jeroen/Documents/Master/Adversarial Analysis/wandb/run-20220204_160530-1o949dt7/logs/debug.log
2022-02-04 16:05:30,689 INFO    MainThread:31917 [wandb_init.py:_log_setup():372] Logging internal logs to /home/jeroen/Documents/Master/Adversarial Analysis/wandb/run-20220204_160530-1o949dt7/logs/debug-internal.log
2022-02-04 16:05:30,691 INFO    MainThread:31917 [wandb_init.py:init():404] calling init triggers
2022-02-04 16:05:30,691 INFO    MainThread:31917 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'model_name': 'tiny_bert', 'dataset_name': 'cad_snli_original', 'seed': 42, 'epochs': 10, 'batch_size': 32, 'lr': 0.0001, 'lr_scheduler': 'cosine', 'betas': (0.9, 0.999), 'weight_decay': 0, 'warmup_steps': 207, 'device': device(type='cuda', index=0)}
2022-02-04 16:05:30,692 INFO    MainThread:31917 [wandb_init.py:init():460] starting backend
2022-02-04 16:05:30,692 INFO    MainThread:31917 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-04 16:05:30,769 INFO    MainThread:31917 [backend.py:ensure_launched():216] starting backend process...
2022-02-04 16:05:30,834 INFO    MainThread:31917 [backend.py:ensure_launched():221] started backend process with pid: 31958
2022-02-04 16:05:30,838 INFO    MainThread:31917 [wandb_init.py:init():469] backend started and connected
2022-02-04 16:05:30,863 INFO    MainThread:31917 [wandb_init.py:init():533] updated telemetry
2022-02-04 16:05:31,006 INFO    MainThread:31917 [wandb_init.py:init():563] communicating current version
2022-02-04 16:05:33,112 INFO    MainThread:31917 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-04 16:05:33,112 INFO    MainThread:31917 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-04 16:05:33,433 INFO    MainThread:31917 [wandb_init.py:init():606] starting run threads in backend
2022-02-04 16:05:38,446 INFO    MainThread:31917 [wandb_run.py:_console_start():1810] atexit reg
2022-02-04 16:05:38,448 INFO    MainThread:31917 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-02-04 16:05:38,449 INFO    MainThread:31917 [wandb_run.py:_redirect():1689] Redirecting console.
2022-02-04 16:05:38,455 INFO    MainThread:31917 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-04 16:05:38,455 INFO    MainThread:31917 [wandb_init.py:init():633] run started, returning control to user process
2022-02-04 16:05:49,524 INFO    MainThread:31917 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-02-04 16:05:49,531 INFO    MainThread:31917 [wandb_run.py:_restore():1752] restore
2022-02-04 16:05:54,942 ERROR   MainThread:31917 [wandb_run.py:_atexit_cleanup():1798] Problem finishing run
Traceback (most recent call last):
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1934, in _on_finish
    self.history._flush()
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1017, in _history_callback
    self._backend.interface.publish_history(
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 505, in publish_history
    item.value_json = json_dumps_safer_history(v)  # type: ignore
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/site-packages/wandb/util.py", line 761, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/site-packages/wandb/util.py", line 728, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/jeroen/miniconda3/envs/adversarial/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataLoader is not JSON serializable
